# Generated by Django 4.2.16 on 2024-09-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_owner_ownerface_image_owner_ownerfingerprint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='ownerface_image',
            new_name='face_image',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='ownerfingerprint',
            new_name='fingerprint',
        ),
    ]
