# Generated by Django 4.2.16 on 2024-10-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_ownerface_image_owner_face_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='boarder_face',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
