# Generated by Django 4.2.16 on 2024-10-29 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_tenant_boarder_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='pay_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
