# Generated by Django 4.2.16 on 2024-10-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_tenant_pay_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='pay_date',
        ),
        migrations.AddField(
            model_name='tenant',
            name='duedate_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
