# Generated by Django 4.2.16 on 2024-11-11 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_tenant_pay_date_tenant_duedate_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='tenant',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
